### ISSUE TITLE
Menu does not fit on the screen

### ISSUE THREAD

**Issue by xorock** [zendframework/zend-form#101]
https://zendframework.github.io/zend-form/

Both submenus for "elements" and "view helpers" does not fit on the screen (FHD) and there is no easy way to get list of all elements. ol.breadcrumb is not clickable.

This will apply to all documentation pages.

**Comment by froschdesign** [comment]
Maybe the the old structure would help to break the long lists:

- Reference
   - Elements
       - Intro
       - Element Base Class
       - Standard Elements
           - Button
           - …
       - HTML5 Elements
           - …
   - View Helpers
       - Intro
       - Abstract Helper
       - Standard Helpers
          - formInput
          - …
       - HTML5 Helpers
           - …
       - Upload Progress Helpers
           - …

Compare with https://framework.zend.com/manual/2.4/en/modules/zend.form.view.helpers.html

**Comment by froschdesign** [comment]
This is the wrong issue tracker for this problem. Moved to zendframework/zf-mkdoc-theme#22

Thanks for reporting!
