### ISSUE TITLE
BC break introduced in 2.8.4

### ISSUE THREAD

**Issue by davidwindell** [zendframework/zend-form#102]
I've just been embarrassed on live site (yes, test case added now ;) by a BC break that was introduced in 2.8.4.

This was caused by #19.

Because empty array's are now sent to the hydrator for a Collection (even when the collection's key is not in the validationGroup) all values in that collection are being wiped out. This was not the case in 2.8.3.

I'm not sure at the moment what the solution is as I'm still trying to get my head around why #19 was done.

Thoughts please @weierophinney @svycka @bakura10

**Comment by davidwindell** [comment]
What you are saying [here] (https://github.com/zendframework/zend-form/commit/82b0cdcad2be8313f78bc53eb4d775fc243281cf#diff-bf24109586ef9fc93a5938f683958d82R573) is that because nothing was posted for a collection element, you should pass that to the hydrator as an empty array.

I have many forms where we don't display the collections on the same page (and thus they are not posted - but should never be deleted like this). 

How should we work around this?

**Comment by svycka** [comment]
@davidwindell can you show example what does not work because I not fully understand where is the problem I thought that inputFitler is responsible for validationGroup but I guess I was wrong :(

**Comment by davidwindell** [comment]
@svycka the idea of the validation group is that if you omit a field (or say a collection) then that data won't be validated or then consequently hydrated. 

What's happening now is even when a collection is explicitly not included in the validationGroup it is being sent through with the data to the hydrator as empty. 

I'll push up a breaking test.

**Comment by svycka** [comment]
@davidwindell you are right this really does not work with validationGroup, but I am not sure how to fix it yet. 
@weierophinney any suggestions? maybe we can pass validation group as optional second param in bindValues()? would it be BC break?

**Comment by davidwindell** [comment]
Please see #103 for a test case that passes in 2.8.3 but not 2.8.4+

**Comment by netiul** [comment]
I'm having the same issue.

**Comment by popovsergiy** [comment]
New problem is raised after this fix.
I have big form with nested fieldset collections
**InvoiceForm->InvoiceFieldset (base) -> InvoiceProductFieldset (collection) -> QuantityItemFieldset (collection)**

I set group validation like this
```
$form->setValidationGroup([
	'invoice' => [
		'invoiceProducts' => [
			'quantityItems' => [
				'id',
				'quantity'
			]
		]
	]
]);
```
When I called ```$form->isValid()``` post data hydrate to entity successfully.
This scenario has been worked correct to 2.9.1 release.
Now, when I call this code it [simply iterate through base fieldset elements](https://github.com/zendframework/zend-form/blob/master/src/Fieldset.php#L573-L575) and nothing to do with nested fieldsets.

**Comment by webimpress** [comment]
@popovsergiy Could you open separate issue and provide a test, which pass on version <2.9.1 and fails on 2.9.1? Thanks!

**Comment by davidwindell** [comment]
Yes, I'm experiencing this too.

**Comment by svycka** [comment]
can someone create a test case for this? @davidwindell ?

**Comment by popovsergiy** [comment]
@svycka, I will try create test but not sure what to do after. Simply create PR?

**Comment by svycka** [comment]
yep, I would like to see where it fails and maybe we can fix it.
