### ISSUE TITLE
Square brackets in name of form element

### ISSUE THREAD

**Issue by albrin** [zendframework/zend-form#107]
How can I use square brackets in name of form element?

```
$element = new Element\Text();
$element->setName('type1[FIO]');
// ...
$personalType1->add($element);
```

Render form

```
...
<input type="text" value="" placeholder="Ф.И.О." id="personalType1FIO" class="form-control order-group__input" name="type1[FIO]">
...
```

$_POST ($request->getPost()->toArray())

```
Array
(
    [type1] => Array
        (
            [FIO] => My FIO
        )
)
```

But when I do fill and submit the form - not the values are set and the form does not pass validation.

```
$personalType1->setData($request->getPost());
```

**Comment by robertboloc** [comment]
You need to use [Collections](https://zendframework.github.io/zend-form/collections/) for this functionality. `type1` becomes your collection and `FIO` is an item in this collection

**Comment by weierophinney** [comment]
You can accomplish this with fieldsets. When you add a fieldset to a form (or even another fieldset), it gets nested in the way you indicated, causing array notation in the client.

**Comment by froschdesign** [comment]
Closing because question was answered.

**Comment by stephaneeybert** [comment]
What about the ajax route ? Any way ?

This array item:
`'clients[0]': $('[name="clients[0]-' + id + '"]').val()
`
gets its closing square bracket stripped away.

**Comment by froschdesign** [comment]
@stephaneeybert 
Sorry, but I think this is the wrong place for question. There is no Ajax or JavaScript.
