### ISSUE TITLE
setMessages not working properly

### ISSUE THREAD

**Issue by googlle** [zendframework/zend-form#11]
Hello.

I tried to validate my form.
In controller I use this code
```php
if ($formUrl != $url) {
	$form->get('url')->setMessages(array('Link is wrong'));
}

if ($form->isValid()) {
	echo 'validate';
}
```
If I set "setMessages" - form is validate, but form must not be validate

**Comment by akrabat** [comment]
`setMessages` doesn't force the form to be invalid. You need to tell the input filter that the element is invalid. I suspect that the easiest way to do this is to use a `Regex` validator.

**Comment by froschdesign** [comment]
> If I set "setMessages" - form is validate, but form must not be validate

The code documentation says something different:

```php
/**
 * Set a list of messages to report when validation fails
 */
public function setMessages($messages) {}
```
https://github.com/zendframework/zend-form/blob/master/src/Element.php#L479

**Comment by googlle** [comment]
Thank you. I understand. Can you tell how to call the error before the validate?

**Comment by Maks3w** [comment]
I understand the question. Sometimes it's very complex to define when the input is invalid, in special when there are business rules in the game (user does not have  enough balance or this is valid if other product was acquired before) 

You could replace the input validator with a validator which always fail. You can achieve this with Zend\Validator\Callback or create your own.

**Comment by googlle** [comment]
Thanks. Close this issue
