### ISSUE TITLE
Multi-select doesn't validate because InArray doesn't take arrays as values

### ISSUE THREAD

**Issue by bitwombat** [zendframework/zend-form#127]
If I have a select form element with an attribute of 'multiple'  => 'true', then InArray#isValid gets called with $value set to an array.

However, that method doesn't support iterating through $value's elements.  $value is assumed to be a scalar.

Bug or am I using it wrong?

**Comment by froschdesign** [comment]
> However, that method doesn't support iterating through $value's elements.

The [`Explode` validator](https://github.com/zendframework/zend-validator/blob/master/src/Explode.php) is used.

> am I using it wrong

Maybe.
Can you show your usage with a short code example? Thanks!

**Comment by bitwombat** [comment]
Working on getting one together...

**Comment by bitwombat** [comment]
I'm trying hard to know what what I'm talking about but I'm not there yet.  Bear with me.

I've made an overblown MVC testcase at:  https://github.com/bitwombat/inarray_test

If you clone that, serve it, and navigate to http://localhost/form
you'll get this simple form:
![image](https://cloud.githubusercontent.com/assets/3937658/20638615/5a3a5ea2-b400-11e6-8032-b73e22d2665f.png)

You can see "two" is selected.  That's from this line in the attributes for the select element:
     'value_options' => ['one', 'two', 'three']

Some part of the form creation process causes the InArray validator to get added to the chain.  I don't know about the Explode validator you've mentioned above.  

So, then [here in InArray](https://github.com/zendframework/zend-validator/blob/master/src/InArray.php#L220), 
$value is

    [
        [0] => "1"
    ]

and

$hackstack is 

    [
        [0] => 0
        [1] => 1
        [2] => 2
    ]

It seems odd that the haystack isn't ['one', 'two', 'three'].  Regardless, the in_array test fails (it can search for an element in the haystack, or an entire array in the haystack, but it doesn't iterate the input array).  And so the form error reports:

"The input was not found in the haystack".

Which was actually the beginning of this journey :)

Thanks for looking.

**Comment by epoleacov** [comment]
@bitwombat Please use boolean true or "multiple" in "multiple" attribute value not "true" as string, you forced "multiple" HTML attribute with string value, but not switched Zend\Form\Element\Select to multiple mode.

**Comment by froschdesign** [comment]
The boolean value `true` also works.

Example:
```php
$form = new Zend\Form\Form();
$form->add(
    [
        'name'       => 'foo',
        'type'       => Zend\Form\Element\Select::class,
        'options'    => [
            'value_options' => [
                'one',
                'two',
                'three',
            ],
        ],
        'attributes' => [
            'multiple' => true,
        ],
    ]
);

$form->setData(
    [
        'foo' => 1,
    ]
);

var_dump($form->isValid()); // true

$form->setData(
    [
        'foo' => [
            0,
            1,
            2,
        ],
    ]
);

var_dump($form->isValid()); // true

$form->setData(
    [
        'foo' => [
            4,
            5,
        ],
    ]
);

var_dump($form->isValid()); // false
```
