### ISSUE TITLE
Are Decorators gone?

### ISSUE THREAD

**Issue by divix1988** [zendframework/zend-form#128]
Hi,

I am moving from Zend 1 to Zend 3 atm and I can't find ay documentation about decorators in ZF3, 
Have they been removed?

Thanks,

**Comment by tdutrion** [comment]
Yes, they have indeed been removed in ZF2, and ZF3 is just a continuation of ZF2.

What were you trying to achieve? You probably need to change the view helper to match the rendering you want, but I may be wrong depending on your specifics.

**Comment by divix1988** [comment]
@tdutrion Do you know if I can specify presentation layer in Form object itself (or like you mentioned in view form helper)? As I don't want to provide another .phtml for rendering my form. 

I would like to achieve the same results as in Zend 1, so when forms where self-contained.

**Comment by tdutrion** [comment]
Any chance you have an example of what you are trying to do? Just the markup of the output would be great.

Rendering is done within the View Helpers (in the render methods). Each element provides its own.
Example: [form helper input](https://github.com/zendframework/zend-form/blob/master/src/View/Helper/FormInput.php#L130).

If you create a new view helper (same name different module), then use your configuration (view_helpers key) to set the right name to your new helper (or its factory), that should work.
Here is how you do your config array: [Registering view helper](https://framework.zend.com/manual/2.4/en/modules/zend.view.helpers.advanced-usage.html#registering-helpers)
Here is where the helpers are registered: [Zend From ConfigProvider](https://github.com/zendframework/zend-form/blob/master/src/ConfigProvider.php#L261)

Obviously, your custom module must be registered after the default one.

The invokables from the doc do not exist anymore.
```
<?php

return [
    'view_helpers' => [
        'factories' => [
            View\Helper\Form::class => MyModule\View\Helper\FormFactory::class,
        ],
   ],
];
```

```
<?php

namespace MyModule\View\Helper;

use Interop\Container\ContainerInterface;

class FormFactory
{
    public function __invoke(ContainerInterface $container)
    {
        return new Form();
    }
}
```

And then you do your form element (pro tip, your Form helper extends the main Form helper and only override render()).

**Comment by divix1988** [comment]
Thanks man, override default Form View Helper did the trick. cheers!
