### ISSUE TITLE
Zend Form requires ServiceManager but doesn't require it (Fatal Error)

### ISSUE THREAD

**Issue by markkimsal** [zendframework/zend-form#132]
running
`composer require -vvv zendframework/zend-form`
will result in an immediate fatal error on your project.

> Fatal error: Class 'Zend\ServiceManager\AbstractPluginManager' not found 

autoload/formElementManagerPolyfill.php uses Zend\ServiceManager\ServiceManager but this package is not required in the composer file, it is merely suggested.

**Comment by Ocramius** [comment]
Probably time that we simply add the dependency, rather than polyfilling it...

**Comment by froschdesign** [comment]
Duplicate of #72
