### ISSUE TITLE
Form::getMessages() on plain array collection

### ISSUE THREAD

**Issue by vaclavvanik** [zendframework/zend-form#135]
Hi, I have problem with getting form error messages on plain array collection (collection with text inputs and `InputFilter\ArrayInput`).

Whole example is in [gist](https://gist.github.com/vaclavvanik/477cc7d62d0d318d71a4e955354f8794).

Is this bug or my configuration is bad?

**Comment by froschdesign** [comment]
@vaclavvanik 
I think, it duplicates #26

**Comment by vaclavvanik** [comment]
Current behavior is imho bug. Should I create PR?

**Comment by froschdesign** [comment]
> Current behavior is imho bug.

Right!

> Should I create PR?

Go for it! 👍

**Comment by vaclavvanik** [comment]
Created #136
