### ISSUE TITLE
Can instructions sent via Annotations be overriden programmatically?

### ISSUE THREAD

**Issue by dennis-fedco** [zendframework/zend-form#144]
Annotations allows you to do this:

    /**
     * @ComposedObject({
     *     "target_object":"Namespace\Model\ComposedCollection",
     *         "is_collection":"true",
     *         "options":{"count":2}
     *     }); 
     */ 

Which allows a static count of 2.  I need a variable `count`, to where I specify `count` at run time.
Is there a way to override `count` programmatically?

**Comment by froschdesign** [comment]
@dennis-fedco 
> Is there a way to override count programmatically?

Get the element from the form and [set the `count` option](https://github.com/zendframework/zend-form/blob/master/src/Element/Collection.php#L290).
