### ISSUE TITLE
Can Hydrator\ClassMethods constructor parameter be set to false via Annotations?

### ISSUE THREAD

**Issue by dennis-fedco** [zendframework/zend-form#145]
I use Annotations to specify a ClassMethods Hydrator is like so:

    /**
     * @Annotation\Hydrator("Zend\Hydrator\ClassMethods")
     */
    class MyEntity{}

`ClassMethods`'s constructor accepts a single parameter of `$underscoreSeparatedKeys`, which is set to `true` by default.  Is there a way to override it to be `false` via Annotations?

**Comment by froschdesign** [comment]
@dennis-fedco 
You can find the answer at the unit tests: https://github.com/zendframework/zend-form/blob/master/test/TestAsset/Annotation/EntityWithHydratorArray.php#L17
