### ISSUE TITLE
Does Fieldset::populateValues() have a way to specify a NamingStrategy?

### ISSUE THREAD

**Issue by dennis-fedco** [zendframework/zend-form#146]
Relevant code for question:  https://github.com/zendframework/zend-form/blob/release-2.10.0/src/Fieldset.php#L392-L393

I am running into a situation where `$this->iterator` contains keys like 'myCamelCaseName', since that is what I named my keys, but my `$data` contains keys like `my_camel_case_name`, due to my `ClassMethods` hydrator using `UnderscoreNamingStrategy` and converting my keys to use underscores.

The result is -- my binded object does not get populated with values, since keys do not match (`$valueExists` == false).

My question is -- is there a way for `$iterator` to abide by a naming strategy, or have a conversion factor of some kind?  The only way I see to for my object to populate correctly is to remove `UnderscoreNamingStrategy` from my hydrator for the keys to match.  But if I want to keep that strategy, is there an alternative solution?

**Comment by froschdesign** [comment]
@dennis-fedco 
>  is there a way for $iterator to abide by a naming strategy, or have a conversion factor of some kind?

No.

> But if I want to keep that strategy, is there an alternative solution?

For example one of these:

- Use snake case strings (e.g. `foo_bar`) for your form element names.
- Create your own naming strategy with asymmetrical mapping.
- Use different hydrators between TableGateway and your forms.

**Comment by dennis-fedco** [comment]
Thanks!

But can you please help clarify when or how the `ClassMethods` hydrator works with underscores?

First, relevant code from `Form::bind()`:
https://github.com/zendframework/zend-form/blob/release-2.10.0/src/Form.php#L303-L305

I have a populated domain object entity and I do `$form->bind($object)`.
When I use `{"underscoreSeparatedKeys": false}`, all seems to work out well.  That is:

1. `extract()` transforms `$object` into an array with my camelCase values
2. `populateValues()` takes array in 1 and populates the form properly and all is well

But when I use `{"underscoreSeparatedKeys": true}`, this breaks down.

1. `extract()` transforms `$object` into an array with snake_case keys, and when there is a mismatch between camelCase and snake_case keys, then `extract()` fails to recurse into fieldsets and fails to extract those values, so it leaves my private properties as-is, unextracted.
2. `populateValues()` then fails to populate the form because of the key mismatches

To put it bluntly,... what good is `ClassMethods` with underscore strategy being true, when it creates key mismatches causing above breakdown?  Is it thus asymmetrical?  Am I using it incorrectly or missing something?  Am I placing incorrect runtime flow expectations on how to use `bind()`, `extract()` and `populateValues()`?

**Comment by froschdesign** [comment]
@dennis-fedco 

> …and when there is a mismatch between camelCase and snake_case keys

Why is there "mismatch"? This questions should be answered!

**Comment by dennis-fedco** [comment]
Because "camelCase" != "camel_case", and because my assumption that `$this->extract()` and `$this->populateValues()` use the `ClassMethods(true)` symmetrically is wrong.

There is no mismatch when UnderscoreNamingStrategy is not active.

**Comment by froschdesign** [comment]
> and because my assumption that $this->extract() and $this->populateValues() are using ClassMethods(true) symmetrically is wrong.

Please provide a short and reproducible example.

**Comment by dennis-fedco** [comment]
Please see https://gist.github.com/dennis-fedco/70c88db925de6a5a5dc07d6085316487

**Comment by froschdesign** [comment]
@dennis-fedco 
> 1. First, run as-is. Expected Output is "Object validated successfully"
> 2. Change "{"underscoreSeparatedKeys": false}" to "{"underscoreSeparatedKeys": true}
> 3. Run again.
>  - Expected output: "Object validated successfully"
>  - Actual output: "Object validation failed"

Why should the second run work? There are no keys separated by underscores. 

The `AnnotationBuilder` extracts all properties of your entity classes and uses these to create the form element names. In your case:

* `motorInput`
  * `motorVoltage`
  * `motorHz`

No keys separated by underscores and so no need to use the naming strategy `UnderscoreNamingStrategy`.

**Comment by dennis-fedco** [comment]
ah okay it make more sense now.  I thought it was doing something else, like change my camel case names to underscores and back.  It expects underscores from the get go instead.
