### ISSUE TITLE
How do you set count on a Collection that is part of another Collection?

### ISSUE THREAD

**Issue by dennis-fedco** [zendframework/zend-form#151]
I wrote a Form with Annotations that has a Collection of elements.  Each Collection in turn has a Collection.

I was able to use `setCount` on the first level Collection, but unable to `setCount` on the child Collections.  I tried `getFieldsets()` on the main Collection but it returns an empty array (array of count 0), when I expected an array of Fieldsets.  Am I doing something wrong?

Here is a code example I have:
https://gist.github.com/dennis-fedco/4915cf8ee110f85c9840bfd3a66e1886

Look for "ACTUAL" and "EXPECTED" text where unexpected result happens.

**Comment by froschdesign** [comment]
@dennis-fedco 
> I tried `getFieldsets()` on the main Collection

A `Collection` element is added as normal element and so `getFieldsets()` is wrong. Use the `get` method to fetch your collection.

**Comment by dennis-fedco** [comment]
I tried `$form->get('categories')->get('subCategories');` but it throws an error:

>Fatal error: Uncaught Zend\Form\Exception\InvalidElementException: No element by the name of [subCategory] found in form 

Code where the element is named is here:  https://gist.github.com/dennis-fedco/4915cf8ee110f85c9840bfd3a66e1886#file-nestedcollectionsetcount-php-L80

**Comment by dennis-fedco** [comment]
Thanks, but I'm still having trouble.. 

        $categories = $form->get('categories');
        
        /*
         * Works
         */
        $categories->setCount(1);
        foreach ($categories->getIterator() as $category)
            /*
             * Has no effect
             */
            $category->get('subCategories')->setCount(5);
        
        /*
         * prints 0
         */
        print($categories->getIterator()->count());

**Comment by froschdesign** [comment]
```php
$form->get('categories')->getTargetElement()->setCount(5);
```

**Comment by dennis-fedco** [comment]
I get 

    Call to undefined method Zend\Form\InputFilterProviderFieldset::setCount()

`$form->get('categories')->getTargetElement()` returns an `InputFilterProviderFieldset` instance and it does not have a method called `setCount`.

I currently no longer need a solution to this, but I stumbled on something that may be related..
I have had some success when I used my setter method to set SubCategories and pass it an array of `SubCategory` elements, and then call `$form->bind()`.  In other words, passing an array with N elements, internally adjusted collection size to N.

**Comment by dennis-fedco** [comment]
I had more success with 

    $form->getTargetElement()->get('categories')->setCount(5);

instead of

    $form->get('categories')->getTargetElement()->setCount(5);

**Comment by froschdesign** [comment]
@dennis-fedco 
Right!

**Comment by froschdesign** [comment]
> ```php
> $form->getTargetElement()->get('categories')->setCount(5);
> ```

Your `$form` variable doesn't include a `Zend\Form\Form` object. Only the `Collection` element has got a method with name [`getTargetElement`](https://github.com/zendframework/zend-form/blob/master/src/Element/Collection.php#L337).
