### ISSUE TITLE
Is there a way to create single radio button that span across fieldsets?

### ISSUE THREAD

**Issue by dennis-fedco** [zendframework/zend-form#153]
For example, see this gist (should be self-contained and runnable)

https://gist.github.com/dennis-fedco/f620477d3969a0eba4a60ffc09cf630e

In the gist I have collection of fieldsets of categories, where each category has a collection of fieldsets of subCategories.  Inside SubCategories, I have a radio button.  Each radio button is (currently) independent of each other, that is you can select more than one.

What I want to be able to select a subCategory via the radio button, and signal to recipient that a single SubCategory has been selected to where a standard radio behavior is possible (can select only one SubCategory).   Is this posisble?  How would you advise to go about it?

**Comment by froschdesign** [comment]
@dennis-fedco 
> see this gist (should be self-contained…)

I am sorry, but your example uses annotations and a controller. This is to complicated. Please reduce _all_ your examples – this is not the first one with annotations, without a questions related to annotations.

Look also at: #155

**Comment by dennis-fedco** [comment]
My use case is a need to indicate a single category, where I can only select one such category.
  
So far if I use a Collection and a Radio button, each Radio button comes out independent, when I need it to be shared.

    /**
     *
     * @var Zend\Form\Element\Radio $radio
     */
    $radio = new Element\Radio('category');
    $radio->setLabel('Category');
    $radio->setValueOptions([
        '0' => 'Mark this as a single selected Category'
    ]);
    
    /**
     * Collection
     *
     * @var Zend\Form\Element\Collection $container
     */
    $container = new Element\Collection('Container');
    $container->setLabel('Container');
    $container->setCount(3);
    $container->setTargetElement($radio);
    $container->setShouldCreateTemplate(true);
    
    $form = new Form('my-form');
    $form->add($container);

I want to have _single_ radio button shared across collection, where I am able to records position of the selected category.  i.e. if I click 2nd radio button, I want to indicate to my back-end script that I have selected the 2nd category in the collection.

You can call it "Shared Radio Button" case.
