### ISSUE TITLE
bind() does not go into the fieldset

### ISSUE THREAD

**Issue by modir** [zendframework/zend-form#196]
- [X] I was not able to find an [open](https://github.com/zendframework/zend-form/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-form/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [X] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

I have a simple form with several text input fields. I would like to present them in the view in two different columns and hence I have two fieldsets.

### Code to reproduce the issue

```php
class CarForm extends Form
{
    public function __construct($name = null)
    {
        parent::__construct('car');

        $brandSection = new Fieldset('brand-section');

        $brandSection->add([
            'name' => 'brand',
            'type' => 'text',
			'attributes' => [
				'id'  => 'brand',
				'placeholder' => 'Brand',
			],
            'options' => [
                'label' => 'Brand',
            ],
        ]);

        $this->add($brandSection);

        $ownerSection = new Fieldset('owner-section');

        $ownerSection->add([
            'name' => 'owner',
            'type' => 'text',
			'attributes' => [
				'id'  => 'owner',
				'placeholder' => 'Owner',
			],
            'options' => [
                'label' => 'Owner',
            ],
        ]);

        $this->add($ownerSection);

    }
}
```
The controller has then this code:
```php
$carForm = new CarForm();
$car = $this->carTable->getCar($id);
$carForm->bind($car);
```
And in the view I have this code:
```php
	$carForm->prepare();
	echo $this->form($carForm);
```

The $car is of this class:
```php
class Car implements InputFilterAwareInterface
{
    public $id;
    public $brand;
    public $owner;

    public function exchangeArray(array $data)
    {
        $this->id     = !empty($data['id']) ? $data['id'] : null;
        $this->brand = !empty($data['brand']) ? $data['brand'] : null;
        $this->owner  = !empty($data['owner']) ? $data['owner'] : null;
    }

    public function getArrayCopy()
    {
        return [
            'id'     => $this->id,
            'brand' => $this->brand,
            'owner'  => $this->owner,
        ];
    }
// Here are some more methods exactly like in the Quick Start Guide ZF3
}
```
In general I can say I created simple app based on the Getting Started tutorial and all I want to change is to have the form elements in two rows and this should be done with fieldsets.

### Expected results

I expected that the form fields are prefilled with the content from the car model. In the [quick start guide](https://docs.zendframework.com/zend-form/quick-start/#binding-an-object) it is written that "If a form contains a fieldset that itself contains another fieldset, the form will recursively extract the values." Because of this I assume that the bind() would recursively get into the form and prefill the elements.

In this situation I expect that the content of $car->brand is filled into the form element "brand".

### Actual results

None of the form fields are prefilled. If I change
```php
$brand = new Fieldset('brand-section');

to 
$brand = new Fieldset('brand-section', ['use_as_base_fieldset' => true]);
```

Then one of the two fieldsets are prefilled. But never both of them.

From my point of view it is either a bug in the documentation or in the code.

**Comment by froschdesign** [comment]
@modir 
Sorry, but nobody can reproduce your example, because we do not know your class in `$car` and your example includes only one fieldset.

**Comment by modir** [comment]
@froschdesign I extended now my example. In general the whole setup is very simple. You could follow the getting started guide for ZF3 and only separate the form fields into two fieldsets. I didn't do anything more till now. (In my case I used different names than in the getting started guide but this doesn't interfere with my issue.)

**Comment by froschdesign** [comment]
I see two problems here:

1. `brand-section` and `owner-section` are only defined in your form. Nothing similar can be found in your `Car` class. There is no magic in zend-form or other classes, so in your case the mapping _must_ fail.
2. You want two rows in your output and this should be done with fieldsets. This is the wrong way, because the `fieldset` element has a meaning in HTML for grouping elements. But in your form there is no separate group or elements which presents a set of form controls.
To generate a layout with rows you can use a simple `div` element.

Example:

```html
<div>
    <?= $this->formRow($form->get('brand')) ?>
</div>
<div>
    <?= $this->formRow($form->get('owner')) ?>
</div>
```

No fieldset needed, no misappropriation of HTML elements and no problems with mapping your class to form and vice versa.

**Comment by modir** [comment]
@froschdesign But doesn't the sentence "If a form contains a fieldset that itself contains another fieldset, the form will recursively extract the values." from the documentation mean that my code should work?

And regarding the two points you are mentioning:
1. Can you point me to somewhere in the documentation where it is explained how I need to define it in the `Car` class?
2. In my context the two fieldsets which do group elements which belong together from a user perspective. In the database they are in one table. Hence fieldsets are the right choice in my case. (I only gave here in my example a simplified code.)

It looks to me like all other element classes in zend_form represent an HTML element. But fieldset does more.

**Comment by froschdesign** [comment]
> But doesn't the sentence "If a form contains a fieldset that itself contains another fieldset, the form will recursively extract the values." from the documentation mean that my code should work?

Extracting works, because you don't need an external object or class. But your problem is not extracting, it is the "mapping" between form and your class.

The handling is quite easy, because you can describe your form as an array:

```php
[
    'brand' => [ // Fieldset
        'name' => '…', // Text element
        'logo' => '…', // File element
    ],
    'owner' => [ // Fieldset
        'first-name' => '…', // Text element
        'last-name'  => '…', // Text element
    ],
]
```
The same array can be used / is used to set data to the form and get or populate values.

The `bind` method does not do anything else: extract data from your object and populate values to the form.
So you must provide the same array structure.

**Comment by froschdesign** [comment]
In the documentation you will find a complete example with fieldsets under the topic "Collections": https://docs.zendframework.com/zend-form/collections/
A fieldset for a brand is also included.

**Comment by modir** [comment]
Thanks. But here is exactly the problem. I read this part of the documentation and I see at the beginning of the page the entity class but there are no arrays. The example on this page has two entity classes for two fieldsets. In my case it is one entity class for two fieldsets. Hence the example doesn't work.

**Comment by froschdesign** [comment]
See my comment above with: "The handling is quite easy, because you can describe your form as an array"

**Comment by froschdesign** [comment]
You must adapt the example for your class and follow my explanation:

```php
$form->bind($car);
```

Do the same thing while extracting like this:

```php
$data = $car->getArrayCopy();
$form->populateValues($data);
```

And if you have fieldsets like `brand` and `owner`, then you must provide these also in your array:

```php
[
    'brand' => [
        'name' => '…',
        'logo' => '…',
    ],
    'owner' => [
        'first-name' => '…',
        'last-name'  => '…',
    ],
]
```
