### ISSUE TITLE
Documentation is missing for additional HTML attributes on form view helpers

### ISSUE THREAD

**Issue by froschdesign** [zendframework/zend-form#202]
Version 2.12.0 of zend-form introduces two new methods for view helpers:

```php
$helper->addValidAttribute('attribute-name');
$helper->addValidAttributePrefix('prefix-');
```

These new methods should be added to the documentation with some code examples.

See also:

* [related pull request](https://github.com/zendframework/zend-form/pull/194)
* [release notes of version 2.12.0](https://github.com/zendframework/zend-form/releases/tag/release-2.12.0)

**Comment by weierophinney** [comment]
Beg to differ: these _are_ in the matrix of available methods, as I added them when merging that pull request:

- https://github.com/zendframework/zend-form/commit/2ad2557bb45d720021263e9ad614e9e36282f90d

What we don't have are code examples. That said, we do not have code examples for most of the methods in the abstract  helper.
