### ISSUE TITLE
Documentation is missing for new method setTranslateMessages on FormElementErrors

### ISSUE THREAD

**Issue by froschdesign** [zendframework/zend-form#203]
Version 2.12.0 of zend-form introduces a new method for the `FormElementErrors` view helper:

```php
echo $this->formElementErrors()->setTranslateMessages(false);
```

This new method should be added to the documentation with a code example.

* [related pull request](https://github.com/zendframework/zend-form/pull/188)
* [release notes of version 2.12.0](https://github.com/zendframework/zend-form/releases/tag/release-2.12.0)

**Comment by weierophinney** [comment]
This was documented after the fact, but before the release:

- https://github.com/zendframework/zend-form/commit/c57ba84b6ca9383ad6160f04d49b10f519495ee0
