### ISSUE TITLE
Missing default tel (and search) plugins

### ISSUE THREAD

**Issue by Draxticore** [zendframework/zend-form#233]
As can be seen in:
https://github.com/zendframework/zend-form/pull/57
, the tel and search types have been initially omitted, for whatever reason.
I suggest to update:

src/FormElementManager/FormElementManagerV2Polyfill.php

and

src/FormElementManager/FormElementManagerV2Polyfill.php

, accordingly. If there is consensus on this suggestion, I could try to do it myself.

### Code to reproduce the issue

I have the following config:

```php
    'form' => [
        'elements' => [
            [
                'spec' => [
                    'type' => 'tel',
                    ...
                ],
            ],
        ],
    ],
```

### Expected results

The tel plugin should be found.

### Actual results

Service with name "<ServiceName>" could not be created. Reason: A plugin by the name "tel" was not found in the plugin manager Zend\Form\FormElementManager\FormElementManagerV3Polyfill

**Comment by webimpress** [comment]
@Draxticore would you like submit PR with the fix?

**Comment by Draxticore** [comment]
@webimpress, sure, I'll go ahead, and try to do it!
