### ISSUE TITLE
Collection validation messages

### ISSUE THREAD

**Issue by mbaumgartl** [zendframework/zend-form#26]
I struggle using validators in collections. If a validator in a collection fails, the form is marked as invalid. Unfortunately `getMessages()` returns an empty array and there is no way to provide any feedback to the user.

The problem seems to relate to this [issue](https://github.com/zendframework/zf2/issues/5265). If I hack the `Fieldset` class as mentioned in this [comment](https://github.com/zendframework/zf2/issues/5265#issuecomment-56173075), the errors are available through `getMessages()`.

Is there a better workaround to the problem?

**Comment by froschdesign** [comment]
Fixed with #136
