### ISSUE TITLE
ServiceManager v2-v3

### ISSUE THREAD

**Issue by kynx** [zendframework/zend-form#35]
Anyone else working on this? I've been trying, but I've stalled on https://github.com/zendframework/zend-inputfilter/pull/86 and https://github.com/zendframework/zend-servicemanager/pull/79

I can do a PR with what I've got to date, but it's broken. Let me know.

**Comment by weierophinney** [comment]
We need to get dependencies updated first; work on components that don't
depend on other components with SM/EM refactors.

**Comment by kynx** [comment]
Yeah, been helping out on zend-inputfilter.

**Comment by kynx** [comment]
Speaking of dependencies - every seen one of these?
http://kynx.github.io/DependencyWheel/zend-form-dev.html

Don't know how much use it is, but it sure looks pretty :)

**Comment by weierophinney** [comment]
> Speaking of dependencies - every seen one of these?

No, but that's awesome!

Would be quite interested to see it for production vs dev; most of the components I've been working on during the forwards compatibility migration have very, very few actual requirements, but a ton of development requirements. Curious to see what that looks like!

Thanks for sharing, @kynx !
