### ISSUE TITLE
formRow ViewHelper not reset partial template

### ISSUE THREAD

**Issue by SNikolaus** [zendframework/zend-form#36]
If formRow walks trough an array of elements and one is set to an partial template 
` echo $this->formRow($element,null, null, 'partial/multi-checkbox.phtml'); ` 
next ones also use this template even they are not set
`echo $this->formRow($element, null, true, null);`

**Comment by froschdesign** [comment]
You can use [the `setPartial()` method](https://github.com/zendframework/zend-form/blob/master/src/View/Helper/FormRow.php#L354).

**Comment by SNikolaus** [comment]
thanks, but 
`echo $this->formRow($element)->setPartial(null)->setRenderErrors(true);`
does not work
`Fatal error: Call to a member function setPartial() on string`

The way I found:
`echo $this->formRow($element, null, true, "");`

but it remains a bug I think. Isn't it?

**Comment by froschdesign** [comment]
> ```php
echo $this->formRow($element)->setPartial(null)->setRenderErrors(true);
```

This is wrong!

Use:
```php
$this->plugin('formRow')->setPartial(null);
echo $this->formRow($element)
```

> but it remains a bug I think. Isn't it?

No! [Look at the code.](https://github.com/zendframework/zend-form/blob/master/src/View/Helper/FormRow.php#L103)

**Comment by SNikolaus** [comment]
o.k., thanks :-)

**Comment by froschdesign** [comment]
You're welcome!
