### ISSUE TITLE
Input type "tel" class

### ISSUE THREAD

**Issue by MidnightDesign** [zendframework/zend-form#49]
Is there a specific reason why there is no `Zend\Form\Element\Tel`?

**Comment by weierophinney** [comment]
Yes: nobody has contributed one. :-)

**Comment by MidnightDesign** [comment]
Alright, I'll take that one then. I'll also add a type="search". Anything else missing?

**Comment by froschdesign** [comment]
@MidnightDesign 
View helpers for `tel` and `search` are already available.

For a `tel` element maybe can help the validator `Zend\I18n\Validator\PhoneNumber`. But what would you add to the `search` element?

**Comment by MidnightDesign** [comment]
I didn't think about validators too much. I would just add them for completeness. I add my elements in the form like so:

```php
$this->add([
    'name' => 'my_element',
    'type' => Password::class,
]);
```

And I just think it's weird I can't do that with some types like `'type' => Tel::class` or `Search::class`.

**Comment by MidnightDesign** [comment]
I've opened #57.

**Comment by MidnightDesign** [comment]
#57 has been merged.
