### ISSUE TITLE
How to let zend-form support vue.js element attributes?

### ISSUE THREAD

**Issue by waney** [zendframework/zend-form#50]
How to let zend-form support vue.js element attributes,
 for example: v-mode= ABC "<input"...

**Comment by vitorbarros** [comment]
@waney vue js is similar with angular js that is possible to integrate with zf, so in this case you can use a html file with your form and send a request to zf with inputs and use zend form to help you validate the sent data. If you want i can show you how to do that.

**Comment by froschdesign** [comment]
Fixed with version [2.12.0](https://github.com/zendframework/zend-form/releases/tag/release-2.12.0)

See also: https://docs.zendframework.com/zend-form/helper/abstract-helper/#public-methods
