### ISSUE TITLE
Using Initializers with Composed Object Collections

### ISSUE THREAD

**Issue by PoetikDragon** [zendframework/zend-form#64]
When a form element is created as part of a collection of composed objects, initializers added via config options are not called. I checked the ServiceManager doCreate function when creating these elements, and found that my Closure initializer was not in `$this->initializers` array at all. It is present and initializes correctly with normal (non-collection) composed objects and standard elements.

My initializer:

```
    public function getFormElementConfig()
    {
        return array(
            'initializers' => array(
                'ObjectManagerInitializer' => function ($element, $formElements) {
                    if ($element instanceof ObjectManagerAwareInterface) {
                        $services      = $formElements->getServiceLocator();
                        $entityManager = $services->get('Doctrine\ORM\EntityManager');
                        $element->setObjectManager($entityManager);
                    }
                },
            ),
        );
    }
```

My models:

```
/**
 * @ORM\Entity
 * @ORM\Table(name="trial")
 * @Form\Name("trial")
 * @Form\Hydrator("Zend\Hydrator\ClassMethods")
 */
class Trial
{
    ...

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Application\Entity\TrialDivision", mappedBy="trial")
     * @Form\ComposedObject({"target_object": "Application\Entity\TrialDivision", "is_collection": true})
     * @Form\Options({"label": "Classes", "allow_add": true, "allow_remove": true})
     */
    protected $divisions;

    ...
}
```

```
/**
 * @ORM\Entity
 * @ORM\Table(name="trial_division")
 * @Form\Name("trial_division")
 * @Form\Hydrator("Zend\Hydrator\ClassMethods")
 */
class TrialDivision
{
    /**
     * @var Trial
     *
     * @ORM\Id
     * @ORM\ManyToOne(targetEntity="Application\Entity\Trial", inversedBy="divisions")
     * @ORM\JoinColumn(name="trialId", referencedColumnName="id", nullable=false)
     * @Form\Exclude()
     */
    protected $trial;

    /**
     * @var Division
     *
     * @ORM\Id
     * @ORM\ManyToOne(targetEntity="Application\Entity\Division")
     * @ORM\JoinColumn(name="divisionId", referencedColumnName="id", nullable=false)
     * @Form\Required(true)
     * @Form\Type("Application\Form\Element\ObjectLiveSearch")
     * @Form\Options({"label": "Class", "empty_option": "Select a Class",
     *     "find_method": {
     *         "name": "findBy",
     *         "params": {"criteria": {}, "orderBy": {"name": "ASC"}}
     *     }
     * })
     */
    protected $division;

    ...
}
```

My form element:

```
use DoctrineModule\Form\Element\ObjectSelect;
use DoctrineModule\Form\Element\Proxy;
use DoctrineModule\Persistence\ObjectManagerAwareInterface;
use DoctrineModule\Persistence\ProvidesObjectManager;

class ObjectLiveSearch extends ObjectSelect implements ObjectManagerAwareInterface
{
    use ProvidesObjectManager;

    ...

    /**
     * @return Proxy
     */
    public function getProxy()
    {
        if (!$this->getObjectManager()) {
            throw new \InvalidArgumentException('No object manager provided to the form element');
        }

        if (null === $this->proxy) {
            $this->proxy = new Proxy();
            $this->proxy->setObjectManager($this->getObjectManager());
        }
        return $this->proxy;
    }

    ...
}
```

When I try to build the form for Trial I get the following exceptions:

```
Zend\ServiceManager\Exception\ServiceNotCreatedException

File: /var/www/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:950
Message: An exception was raised while creating "Zend\Form\Element\Collection"; no instance returned

Previous exceptions:

InvalidArgumentException

File: /var/www/module/Application/src/Application/Form/Element/ObjectLiveSearch.php:45
Message: No object manager provided to the form element
```

Note: I have tried using a fieldset class instead of annotating the model, however, I still have the same problem - I need the ObjectManager injected into the object and the initializer that does it isn't called. I dumped $this->initializers inside `doCreate` and found that my initializer is not in the array.

**Comment by PoetikDragon** [comment]
Note: I have tried using a fieldset class instead of annotating the model, however, I still have the same problem - I need the ObjectManager injected into the object and the initializer that does it isn't called.

**Comment by weierophinney** [comment]
Are you sure that your custom initializers are not present in the initalizers array? We [have tests for that behavior](https://github.com/zendframework/zend-form/blob/629215d7fcc79ad1d609163ae04b38470bb59488/test/FormElementManagerFactoryTest.php#L36-L72), which makes me wonder how that could be occuring.

However, I think I may have solved the root problem behind the missing `ObjectManager` with #65; this was due to an order issue in how the initializers were registered. Also of note: the new test in that patch validates that initializers passed to the constructor will be configured, so assuming the `FormElementManagerFactory` tests are properly testing real-world behavior with regards to how the `FormElementManager` is produced, the patch should solve your issue.

**Comment by PoetikDragon** [comment]
Thanks got looking at this so quickly! I updated my zend-form but unfortunately the issue still occurs. I did notice that the order of the initializers in $this->initializers is different now. However, I still only have 3 initializers when it attempts to create the ObjectLiveSearch element inside the fieldset inside the collection. The closure created in the config is not in the array.

There are (correctly) 4 initializers when it attempts to create an ObjectLiveSearch element for the main form. It also has correct initializers when creating a fieldset for a composed object that is NOT a collection.

**Comment by weierophinney** [comment]
@PoetikDragon Can you provide me the initializer configuration you're using, so I can attempt to reproduce the issue?

Also, this patch is on master, but not in a release version yet - how were you testing?

**Comment by weierophinney** [comment]
@PoetikDragon Is your use case similar to that reported in #66, by any chance? If so, that code should give me enough to write a unit test and reproduce the issue. If not, I'd appreciate if you could create a minimal reproduce case for me.

Thanks!

**Comment by PoetikDragon** [comment]
@weierophinney Yes it seems to be similar. I will wait and see if fixing #66 addresses my issue as well, and if not I'll write up that minimal case for you.
