### ISSUE TITLE
Zend\Form\Fieldset bindValues problem 

### ISSUE THREAD

**Issue by denchik63** [zendframework/zend-form#83]
Hi.
Have next structure:

``` php
/**
 * Class Client 
 *
 *  @ORM\Entity
 *  @ORM\Table(name="client ")
 *  @package Admin\Entity
 **/
class Client extends AbstractEntity {

    ...
    ...

    /**
     *  @var MasterPhotoGallery[]|ArrayCollection $photoGalleries
     *  @ORM\OneToMany(targetEntity="Admin\Entity\MasterPhotoGallery", mappedBy="client")
     *  @ZFA\Required(false)
     *  @ZFA\ComposedObject({
     *      "target_object": "Admin\Entity\MasterPhotoGallery",
     *      "is_collection": true,
     *      "options": {
     *          "count": 8,
     *          "label": "Фотогаллереи"
     *      }
     * })
     *  @ZFA\Type("Zend\Form\Element\Collection")
     **/
    private $photoGalleries;

}

/**
 * Class MasterPhotoGallery
 *
 *  @ORM\Entity
 *  @ORM\Table(name="client_photo_gallery")
 *  @ZFA\Instance("Admin\Entity\MasterPhotoGallery")
 *  @ZFA\Type("Zend\Form\Fieldset")
 **/
class MasterPhotoGallery extends AbstractEntity {

    /**
     * @var string $title
     * @ORM\Column(type="string", nullable=false, length=50)
     * @ZFA\Type("Zend\Form\Element\Text")
     * @ZFA\Required(false)
     * @ZFA\Options({
     *      "label": "Заголовок"
     * })
     **/

    private $title;
    ...
    ...
    ...
}
```

On validating form, In bindValues method we have name for **title** in PhotoGallery class like that: "photoGalleries[0][title]". But data array has not that key. He has key **title**. Array values look like:
['photoGalleries' => [0 => 'title']]
Source code (after update to version 2.8.4) in Zend\Form\Fieldset, row 568-569:

``` php
        foreach ($this->iterator as $element) {
            $name = $element->getName(); // photoGalleries[0]['title'] 
            if (!array_key_exists($name, $values)) { // of course key not exists
                if (!($element instanceof Collection)) {
                    continue;
                }
             ...
             ...
             ...
             ...
```

Source code (version 2.8.3) in Zend\Form\Fieldset:

``` php
        foreach ($values as $name => $value) {
            if (!$this->has($name)) {
                continue;
           ...
```

Here we have correct name because it's taken from array. By the way in method **extract** we have same problem.

``` php
        // Recursively extract and populate values for nested fieldsets
        foreach ($this->fieldsets as $fieldset) {
            **$name = $fieldset->getName();**
```

**Comment by froschdesign** [comment]
@diniciacci 
Can you provide an unit test for your problem? This would help to find the affected code. (Please reduce the unit test to a minimum; no annotations etc.)

Thanks!

**Comment by diniciacci** [comment]
@froschdesign I failed up to now to produce one that fails indeed. I will try again. My customer said that the  code was "perfectly working with old version of zf2". Where "old" is likely around 2.3.9 (zendframerowk version before the split).

Will work on that in the following days.

**Comment by diniciacci** [comment]
I am still working on the unit test. I am failing to reproduce the problem. However I found that InputFilterProviderFieldset->prepareElements() 

https://github.com/zendframework/zend-form/blob/4419eef6dbe9d276e7e27c6a25f022be74534959/src/Fieldset.php#L368

ends up calling setName() on the actual element (i.e. \Zend\Form\Element\Text) and so modifying its name to foo[0][bar] format (for nested elements, to avoid clashes).

My theory is that then when binding happens the name have been modified and the $values can't match any of the names apart if the data comes from a form that has the above format. Naturally when calling bind data may come from different sources.

I am progressing slowly due to unknown specifications of the code and some comments or suggestions would be welcome. Meanwhile I keep working on the unit test. I keep the good news for a later time when the test is ready.

Best

**Comment by diniciacci** [comment]
@froschdesign The PR has a unit test for this bug. The bug is not present in the current version. The bug was due to an interaction of prepare() with bindValues().

Notice that tests for the same interaction are missing for:
- populateValues()
- if a validationGroup is present

Thanks

**Comment by diniciacci** [comment]
As a final note notice that https://github.com/zendframework/zend-form/commit/c7867fe415a7636c9c48adeb3e7861f286ee2b50 is the commit that introduced the fix and a test for it.

Deciding if both tests should stay is beyond my knowledge of the code.
