### ISSUE TITLE
Error zend-form in Zend 3 - Could not find a valid ServiceManager for FormElementManager

### ISSUE THREAD

**Issue by francisrod01** [zendframework/zend-form#98]
`[Fri Jul 01 21:08:28.282107 2016] [:error] [pid 14049] [client 192.168.50.1:52830] PHP Fatal error:  Uncaught Zend\\ModuleManager\\Listener\\Exception\\RuntimeException: Could not find a valid ServiceManager for FormElementManager in /home/vagrant/projects/web/zf2/zf2-devmedia/vendor/zendframework/zend-modulemanager/src/Listener/ServiceListener.php:202\nStack trace:\n#0 /home/vagrant/projects/web/zf2/zf2-devmedia/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\\ModuleManager\\Listener\\ServiceListener->onLoadModulesPost(Object(Zend\\ModuleManager\\ModuleEvent))\n#1 /home/vagrant/projects/web/zf2/zf2-devmedia/vendor/zendframework/zend-eventmanager/src/EventManager.php(143): Zend\\EventManager\\EventManager->triggerListeners(Object(Zend\\ModuleManager\\ModuleEvent))\n#2 /home/vagrant/projects/web/zf2/zf2-devmedia/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(129): Zend\\EventManager\\EventManager->triggerEvent(Object(Zend\\ModuleManager\\ModuleEvent))\n#3 /home/vagrant/projects/web/zf2/zf2-devmedia/vendor/zendframework/zend-mvc/src/Application.php(264): Zend\\ModuleManager\\ModuleManager->loadMo in /home/vagrant/projects/web/zf2/zf2-devmedia/vendor/zendframework/zend-modulemanager/src/Listener/ServiceListener.php on line 202
`

**Comment by weierophinney** [comment]
Have you added `'Zend\Form'` to your list of modules?

**Comment by devtosystems** [comment]
Yes, I added.

**Comment by weierophinney** [comment]
Can you please provide me:

- the results of running `composer show`
- the contents of your `config/application.config.php`

Thanks!

**Comment by devtosystems** [comment]
Alright!

`composer show`

```bash
container-interop/container-interop    1.1.0 Promoting the interoperability of container objects (DIC...
zendframework/zend-component-installer 0.3.0 Composer plugin for automating component registration in...
zendframework/zend-config              2.6.0 provides a nested object property based user interface f...
zendframework/zend-escaper             2.5.2
zendframework/zend-eventmanager        3.0.1 Trigger and listen to events within a PHP application
zendframework/zend-filter              2.7.1 provides a set of commonly needed data filters
zendframework/zend-form                2.9.0
zendframework/zend-http                2.5.4 provides an easy interface for performing Hyper-Text Tra...
zendframework/zend-hydrator            2.2.1
zendframework/zend-inputfilter         2.7.2
zendframework/zend-loader              2.5.1
zendframework/zend-modulemanager       2.7.2
zendframework/zend-mvc                 3.0.2
zendframework/zend-router              3.0.2
zendframework/zend-servicemanager      3.1.0
zendframework/zend-stdlib              3.0.1
zendframework/zend-uri                 2.5.2 a component that aids in manipulating and validating » ...
zendframework/zend-validator           2.8.1 provides a set of commonly needed validators
zendframework/zend-view                2.8.1 provides a system of helpers, output filters, and variab...
zfcampus/zf-development-mode           3.0.0 Zend Framework development mode script
```

The content of my `config/application.config.php` is:

```php
<?php
/**
 * If you need an environment-specific system or application configuration,
 * there is an example in the documentation
 * @see http://framework.zend.com/manual/current/en/tutorials/config.advanced.html#environment-specific-system-configuration
 * @see http://framework.zend.com/manual/current/en/tutorials/config.advanced.html#environment-specific-application-configuration
 */
return [
    // Retrieve list of modules used in this application.
    'modules' => require __DIR__ . '/modules.config.php',

    // These are various options for the listeners attached to the ModuleManager
    'module_listener_options' => [
        // This should be an array of paths in which modules reside.
        // If a string key is provided, the listener will consider that a module
        // namespace, the value of that key the specific path to that module's
        // Module class.
        'module_paths' => [
            './module',
            './vendor',
        ],

        // An array of paths from which to glob configuration files after
        // modules are loaded. These effectively override configuration
        // provided by modules themselves. Paths may use GLOB_BRACE notation.
        'config_glob_paths' => [
            realpath(__DIR__) . '/autoload/{{,*.}global,{,*.}local}.php',
        ],

        // Whether or not to enable a configuration cache.
        // If enabled, the merged configuration will be cached and used in
        // subsequent requests.
        'config_cache_enabled' => true,

        // The key used to create the configuration cache file name.
        'config_cache_key' => 'application.config.cache',

        // Whether or not to enable a module class map cache.
        // If enabled, creates a module class map cache which will be used
        // by in future requests, to reduce the autoloading process.
        'module_map_cache_enabled' => true,

        // The key used to create the class map cache file name.
        'module_map_cache_key' => 'application.module.cache',

        // The path in which to cache merged configuration.
        'cache_dir' => 'data/cache/',

        // Whether or not to enable modules dependency checking.
        // Enabled by default, prevents usage of modules that depend on other modules
        // that weren't loaded.
        // 'check_dependencies' => true,
    ],

    // Used to create an own service manager. May contain one or more child arrays.
    //'service_listener_options' => [
    //     [
    //         'service_manager' => $stringServiceManagerName,
    //         'config_key'      => $stringConfigKey,
    //         'interface'       => $stringOptionalInterface,
    //         'method'          => $stringRequiredMethodName,
    //     ],
    // ],

   // Initial configuration with which to seed the ServiceManager.
   // Should be compatible with Zend\ServiceManager\Config.
   // 'service_manager' => [],
];
```

and the content of my `config/modules.config.php` is:

```php
<?php
/**
 * @link      http://github.com/zendframework/ZendSkeletonApplication for the canonical source repository
 * @copyright Copyright (c) 2005-2016 Zend Technologies USA Inc. (http://www.zend.com)
 * @license   http://framework.zend.com/license/new-bsd New BSD License
 */

/**
 * List of enabled modules for this application.
 *
 * This should be an array of module namespaces used in the application.
 */
return [
    'Zend\Form',
    'Zend\InputFilter',
    'Zend\Filter',
    'Zend\Hydrator',
    'Zend\Router',
    'Zend\Validator',
    'Application',
];
```

Observation: `zend-form` is with bug.

## ZF3 code refactoring

Here we report the list of ZF2 components to be refactored with the new zend-servicemanager and zend-eventmanager of ZF3.

https://github.com/zendframework/maintainers/wiki/ZF3-code-refactoring

**Comment by stanislas-prime** [comment]
Remove files from `data/cache` directory.

**Comment by greieras** [comment]
Great stanislas-prime

**Comment by settermjd** [comment]
Thanks @stanislas-prime. Coming back to working with Zend Framework 2, that file's been a definite gotcha for me.

**Comment by chander-prakash** [comment]
`I'm having the same issue, there is no cache file, I also added Module in module.config but it won't showing when I hit composer show`
Below is my composer show reponse.....

container-interop/container-interop    1.2.0 Promoting the interoperability...
psr/container                          1.0.0 Common Container Interface (PH...
zendframework/zend-component-installer 1.0.0 Composer plugin for automating...
zendframework/zend-config              2.6.0 provides a nested object prope...
zendframework/zend-escaper             2.5.2 
zendframework/zend-eventmanager        3.1.0 Trigger and listen to events w...
zendframework/zend-http                2.6.0 provides an easy interface for...
zendframework/zend-loader              2.5.1 
zendframework/zend-modulemanager       2.7.2 
zendframework/zend-mvc                 3.1.0 
zendframework/zend-router              3.0.2 
zendframework/zend-servicemanager      3.3.0 
zendframework/zend-stdlib              3.1.0 
zendframework/zend-uri                 2.5.2 a component that aids in manip...
zendframework/zend-validator           2.9.1 provides a set of commonly nee...
zendframework/zend-view                2.9.0 provides a system of helpers, ...
zfcampus/zf-development-mode           3.1.0 Zend Framework development mod...

**Comment by weierophinney** [comment]
@chander-prakash You will need to install zendframework/zend-mvc-form to get form functionality.

**Comment by froschdesign** [comment]
Problem was solved.

**Comment by mudiyala1211** [comment]
An error occurred
An error occurred during execution; please try again later.
File:
C:\xampp\htdocs\zf3curd\module\Post\src\Model\PostTable.php:15
Message:
Call to a member function select() on null


what is problem I am unable to get idea

**Comment by froschdesign** [comment]
@mudiyala1211 
This is an issue / bug tracker. If you need support, please use the forum: https://discourse.zendframework.com/
