### ISSUE TITLE
Class 'Application\Form\View\Helper\FormRow' not found

### ISSUE THREAD

**Issue by SevenbitsIt** [zendframework/zend-form#99]
I migrated an ZF2 Project to the new ZF3 release and now forms using the view plugin helpers not working anymore. i.e. 

`<?php echo $this->formRow($form->get('company')); ?>`

added     'Zend\Form' to the modules.config.php and also the  "zendframework/zend-component-installer" to composer.json. It may be a configuration issue but i can't find any hint on web.

**Comment by webimpress** [comment]
I've just tried on ZendSkeletonApplication v3 and it works. Do you have definitely enabled module `Zend\Form`? Please check your `config/application.config.php` if you have there:
`'modules' => require __DIR__ . '/modules.config.php',`

If it still doesn't work please provide your `config/application.config.php` and `config/modules.config.php`.

**Comment by SevenbitsIt** [comment]
Thank you for the quick answer. Here are the files.
[config.zip](https://github.com/zendframework/zend-form/files/345932/config.zip)

**Comment by webimpress** [comment]
@SevenbitsIt your configuration looks fine. Can you see any error? Have you tried xdebug it?

**Comment by SevenbitsIt** [comment]
Here is my error page with stacktrace.

[bug.zip](https://github.com/zendframework/zend-form/files/345966/bug.zip)

**Comment by webimpress** [comment]
Hm... it looks for class `Backoffice\Form\View\Helper\FormRow` ... do you have any aliases defined for view helpers? Any invokables?  (section `view_helpers` in your `MODULE/config/module.config.php`)

**Comment by SevenbitsIt** [comment]
You're absolutely right, i replaced content of a module.config.php on migration. Thank you for your help and sorry for wasting your time with my silly bug.

**Comment by webimpress** [comment]
@SevenbitsIt no worries :) Please close if solved
